build:
    environment:
        php: '7.4.0'
            
    tests:
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*